version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: pt
      POSTGRES_PASSWORD: chatpassword
      POSTGRES_DB: ptchat
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: pt
      POSTGRES_PASSWORD: chatpassword
      DB_NAME: ptchat
      REDIS_HOST: redis://redis:6379
      SECRET_KEY: mysecretkeyforjwt
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: http://127.0.0.1:8000
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:

networks:
  mynetwork: