version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: pt
      POSTGRES_PASSWORD: chatpassword
      POSTGRES_DB: ptchat
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ptchat.com
      PGADMIN_DEFAULT_PASSWORD: ptchat
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgres_data:
