"""room user

Revision ID: be0f6cc37c39
Revises: 39d273a32e53
Create Date: 2025-02-12 14:23:48.976220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be0f6cc37c39'
down_revision: Union[str, None] = '39d273a32e53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'rooms', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'user_id')
    # ### end Alembic commands ###
